theme: jekyll-theme-minimal
title: Tapia 2017 Doctoral Consortium
show_downloads: false


description: "<small>
Breakfast: 8:00am - 8:45am <br/><br/>

Opening/Intro: 8:45am - 9:00am <br/>
Session 1: 9:00am - 9:45am (Presentation 1, Presentation 2)<br/>
Session 2: 9:45am - 11:30am (Presentation 3, Presentation 4)<br/>
Coffee break <br/>
Session 3: 11:00pm - 11:45pm (Presentation 5, Presentation 6) <br/>
Session 4: 11:45pm - 12:30pm (Presentation 7, Presentation 8) <br/>

Lunch break: 12:30pm - 1:00pm <br/>

Session 5: 1:00pm - 1:45pm (Presentation 9)<br/>

Coffee break <br/>
Closing: 4:45pm - 5:00pm <br/>

Dinner: 5pm <br/>
</small>"
