theme: jekyll-theme-minimal
title: Tapia 2017 Doctoral Consortium
show_downloads: false

description: "<small>
Breakfast: 8:00am - 8:45am  <br/>
<br/>
Opening/Intro: 8:45am - 9:00am <br/>
Session 1: 9:00am - 10:30am (Presentation 1, Presentation 2)<br/>
Coffee break <br/>
Session 2: 11:00am - 12:30am (Presentation 3, Presentation 4)<br/>
<br/>
Lunch break: 12:30pm - 1:00pm <br/>
<br/>
Session 3: 1:00pm - 2:30pm (Presentation 5, Presentation 6)<br/>
Coffee break** <br/>
Session 4:  2:45pm - 4:45pm ((Presentation 7, Presentation 8, Presentation 9)<br/>
Closing: 4:45pm - 5:00pm <br/>
<br/>
Dinner: 5pm
<br/>
</small>"
